baseurl = "/"
languageCode = "en-us"
title = "Haresh Suppiah"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""


ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/hareshtsuppiah/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/oobidoo"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/hareshsuppiah"
    
[[menu.main]]
    name = "GRS Toolkit"
    url = "/2020/08/07/graduate-research-student-toolkit/"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "HSfavicon.ico"

    [params.logo]
    url = "HSicon.png"
    width = 100
    height = 100
    alt = "Logo"

